theme: jekyll-theme-cayman
title: Resume
description: [Experienced in digital IC design internship and system validation internship <br>Recent ECE graduate with training in digital IC seeking an opportunity to undertake digital IC design/verification internship.]
show_downloads: ["false"]
github:
  repository_url: https://github.com/ZongRuLi