theme: jekyll-theme-cayman
title: Zong-Ru Li
description: [A fresh graduate of Electrical and Computer Engineering seeking an ASIC Design/Verification Intern. I have completed coursework in CPU and memory design. Besides, I developed competence in digital IC design, C/RTL co-verification, and CPU/FPGA system validation from my past internship.]
