theme: jekyll-theme-cayman
title: Zong-Ru Li
description: [Experienced in digital IC design internship and system validation internship, Recent ECE graduate with training in digital IC seeking an opportunity to undertake digital IC design/verification internship.]
github:
  another_url: https://github.com/ZongRuLi